import { NextRequest, NextResponse } from 'next/server'
import { SageMakerRuntimeClient, InvokeEndpointCommand } from "@aws-sdk/client-sagemaker-runtime"

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    // If AWS endpoint is configured, use SageMaker
    if (process.env.AWS_SAGEMAKER_ENDPOINT) {
      const client = new SageMakerRuntimeClient({
        region: process.env.AWS_REGION || 'us-east-1',
        // Credentials are automatically loaded from AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      })

      const { cropType, soilPhLevel, soilMoisture, nitrogen, phosphorus, potassium, temperature, rainfall, humidity } = body;
      const cropMap: Record<string, number> = { wheat: 0, corn: 1, rice: 2, soybeans: 3, cotton: 4 };
      const cropEncoded = cropMap[cropType.toLowerCase()] ?? 0;

      // SageMaker XGBoost expects CSV input (without headers)
      const csvPayload = `${cropEncoded},${soilPhLevel},${soilMoisture},${nitrogen},${phosphorus},${potassium},${temperature},${rainfall},${humidity}`;

      const command = new InvokeEndpointCommand({
        EndpointName: process.env.AWS_SAGEMAKER_ENDPOINT,
        Body: Buffer.from(csvPayload),
        ContentType: "text/csv",
        Accept: "text/csv"
      })

      const response = await client.send(command)
      const resultString = new TextDecoder("utf-8").decode(response.Body)
      
      // XGBoost returns a plain string/CSV of the predicted value
      const predictedYield = parseFloat(resultString.trim())

      return NextResponse.json({
        yieldKgHa: predictedYield,
        confidence: 0.95, // Since it's a real model, we assume high confidence
        message: 'Prediction successfully generated by AWS SageMaker XGBoost Model.',
      })
    }

    // --- FALLBACK: Simulated ML model prediction ---
    const {
      cropType,
      soilPhLevel,
      soilMoisture,
      nitrogen,
      phosphorus,
      potassium,
      rainfall,
      temperature,
      humidity,
    } = body

    const baseYield: Record<string, number> = {
      wheat: 4500,
      corn: 8000,
      rice: 5500,
      soybeans: 3000,
      cotton: 1800,
    }

    let yield_kg_ha = baseYield[cropType] || 4000

    const phFactor = 1 - Math.abs(soilPhLevel - 6.5) * 0.08
    yield_kg_ha *= phFactor

    const moistureFactor = 1 - Math.pow((soilMoisture - 65) / 65, 2) * 0.3
    yield_kg_ha *= moistureFactor

    const nitrogenFactor = Math.min(nitrogen / 120, 1.3) * 0.8 + 0.2
    const phosphorusFactor = Math.min(phosphorus / 35, 1.2) * 0.6 + 0.4
    const potassiumFactor = Math.min(potassium / 180, 1.25) * 0.7 + 0.3

    yield_kg_ha *= nitrogenFactor * phosphorusFactor * potassiumFactor

    const tempFactor = 1 - Math.pow((temperature - 22.5) / 25, 2) * 0.4
    yield_kg_ha *= tempFactor

    const optimalRainfall: Record<string, number> = { wheat: 600, corn: 550, rice: 1000, soybeans: 500, cotton: 700 }
    const optimal = optimalRainfall[cropType] || 600
    const rainfallFactor = 1 - Math.pow((rainfall - optimal) / optimal, 2) * 0.35
    yield_kg_ha *= rainfallFactor

    const humidityFactor = 1 - Math.abs(humidity - 70) * 0.01 * 0.5
    yield_kg_ha *= humidityFactor

    const noise = 0.92 + Math.random() * 0.16
    yield_kg_ha *= noise

    let confidence = 0.75

    if (soilPhLevel < 5 || soilPhLevel > 8) confidence -= 0.1
    if (soilMoisture < 30 || soilMoisture > 90) confidence -= 0.1
    if (temperature < 10 || temperature > 35) confidence -= 0.1
    if (rainfall < 200 || rainfall > 900) confidence -= 0.1

    if (soilPhLevel >= 5.5 && soilPhLevel <= 7.5) confidence += 0.05
    if (soilMoisture >= 50 && soilMoisture <= 75) confidence += 0.05
    if (temperature >= 18 && temperature <= 28) confidence += 0.05
    if (rainfall >= 400 && rainfall <= 800) confidence += 0.05

    confidence = Math.max(0.5, Math.min(0.99, confidence))

    let message = ''
    if (confidence > 0.85) {
      message = 'Excellent conditions detected! Your crop should perform very well.'
    } else if (confidence > 0.75) {
      message = 'Good growing conditions. Monitor soil moisture and nutrients for optimal results.'
    } else if (confidence > 0.65) {
      message = 'Moderate conditions. Consider adjusting irrigation and fertilization strategies.'
    } else {
      message = 'Challenging conditions ahead. Implement adaptive farming practices and careful management.'
    }

    if (yield_kg_ha < baseYield[cropType] * 0.8) {
      message += ' Expected yield is below average - review input conditions.'
    } else if (yield_kg_ha > baseYield[cropType] * 1.2) {
      message += ' Expected yield is above average - excellent farming conditions detected!'
    }

    return NextResponse.json({
      yieldKgHa: Math.max(100, yield_kg_ha),
      confidence: Math.round(confidence * 1000) / 1000,
      message,
    })
  } catch (error) {
    console.error('Prediction error:', error)
    return NextResponse.json(
      { error: 'Failed to generate prediction. If using AWS, check your credentials and endpoint.' },
      { status: 500 }
    )
  }
}
